apiVersion: v1
kind: Service
metadata:
  name: iris-classifier-service
spec:
  type: LoadBalancer 
  selector:
    app: iris-classifier
  ports:
  - protocol: TCP
    port: 80      
    targetPort: 8000 